version: '3'
services:
  proxy:
    image: traefik:v2.9.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=library
    networks:
      - traefik
    volumes:
      - mongo-data:/data/db
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
  book-service:
    image: jsalvador/app-books:1.0.0
    expose:
      - 9000
    deploy:
      replicas: 3
    environment:
      - MONGODB_URI=mongodb://mongo/library
      - SERVER_PORT=8080
    labels:
      - "traefik.http.routers.books.rule=PathPrefix(`/app1`)"
      - "traefik.http.middlewares.books.stripprefix.prefixes=/app1"
      - "traefik.http.routers.books.middlewares=books"
 
    


