version: '3'
services:
  proxy:
    image: traefik:v2.9.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  book-service:
    image: jsalvador/app-books:1.0.0
    expose:
      - 9000
    deploy:
      replicas: 1
    environment:
      - MONGODB_URI=mongodb://mongo/library
      - SERVER_PORT=8080
    labels:
      - "traefik.http.routers.books.rule=PathPrefix(`/app1`)"
      - "traefik.http.middlewares.books.stripprefix.prefixes=/app1"
      - "traefik.http.routers.books.middlewares=books"
    depends_on:
      - mongo
volumes:
  mongodb_data:
    driver: local


